sudo: required
services:
  - docker

before_install:
  - docker build -t idosegev/react-multi-container-app-test -f ./client/Dockerfile.dev ./client

script:
  - docker run idosegev/react-multi-container-app-test npm test -- --coverage --watchAll=false

after_success:
 - docker build -t idosegev/react-multi-container-app-client ./client
 - docker build -t idosegev/react-multi-container-app-nginx ./nginx
 - docker build -t idosegev/react-multi-container-app-server ./server
 - docker build -t idosegev/react-multi-container-app-worker ./worker


#Log in to the Docker CLI
 - echo "$DOCKER_PASS" | docker login -u "$DOCKER_ID" --password-stdin
#Take those images and push them to DockerHub
 - docker push idosegev/react-multi-container-app-client 
 - docker push idosegev/react-multi-container-app-nginx 
 - docker push idosegev/react-multi-container-app-server
 - docker push idosegev/react-multi-container-app-worker 

# deploy:
#   provider: elasticbeanstalk
#   region: "us-west-1"
#   app: "multi-container-app"
#   env: "Multicontainerapp-env"
#   bucket_name: "elasticbeanstalk-us-west-1-665129940264"
#   bucket_path: "multi-container-app"
#   on:
#     branch: master
#   access_key_id: "$AWS_ACCESS_KEY"
#   secret_access_key: "$AWS_SECRET_KEY"