apiVersion: v1
kind: Pod
metadata:
  name: client-pod
  labels:
    component: web
spec:
  containers:
    - name: client
      image: idosegev/react-multi-container-app-worker
      ports:
        - containerPort: 3000